apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  monitoringConsoleRef:
    name: splunk-dev
  smartstore:
    defaults:
      volumeName: app-staging
    indexes:
      - name: windows
        remotePath: windows_index
        volumeName: app-staging
    volumes:
      - name: app-staging
        path: purplesec-splunk-apps/indexes/
        endpoint: https://s3-us-east-1.amazonaws.com
        secretRef: s3-app-secret
