apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  monitoringConsoleRef:
    name: splunk-dev
  smartstore:
    defaults:
      volumeName: my-index-volume
    indexes:
      - name: windows
        remotePath: windows/
        volumeName: my-index-volume
    volumes:
      - name: my-index-volume
        path: purplesec-splunk-indexes/
        endpoint: https://s3-us-east-1.amazonaws.com
        secretRef: s3-app-secret
