apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: cm
  namespace: splunk-operator
  finalizers:
    - enterprise.splunk.com/delete-pvc
spec:
  serviceAccount: eksctl-splunk-dev-5-addon-iamserviceaccount-Role1-GD0M20QYH4UB
  monitoringConsoleRef:
    name: splunk-dev
  smartstore:
    defaults:
      volumeName: purplesec-splunk-indexes
    indexes:
      - name: windows
        remotePath: $_index_name
        volumeName: purplesec-splunk-indexes
    volumes:
      - name: purplesec-splunk-indexes
        provider: aws
        storageType: s3
        region: us-east-1
        path: purplesec-splunk-indexes/
        endpoint: https://s3-us-east-1.amazonaws.com
        secretRef: s3-app-secret
