apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-standalone
  namespace: splunk-operator
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/default-backend: splunk-standalone-standalone-service
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
  - host: splunk.defnotavirus.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk-s1-standalone-service
            port:
              number: 8000

